<a href="https://colab.research.google.com/github/SmurZik/Telecom/blob/main/lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Упражнение 7.1
В блокноте для этой главы, chap07.ipynb, представлены дополнительные примеры и пояснения. Блокнот был просмотрен и код запущен.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Упражнение 7.2
Реализуйте алгоритм Быстрого Преобразования Фурье (БПФ), согласно лемме Дэниелсона-Ланцоша - рекурсивный алгоритм ДПФ. Подробности преобразований, алгоритм и самма лемма представлены в методичке.

Произведём импорт и реализуем алгоритм:

In [ ]:
import numpy as np
PI2 = 2 * np.pi

In [ ]:
ys = [-0.9,0.6,0.7,-0.8]
hs = np.fft.fft(ys)
hs

array([-0.4+0.j , -1.6-1.4j,  0. +0.j , -1.6+1.4j])

In [ ]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

In [ ]:
dft(ys)

array([-0.4+0.00000000e+00j, -1.6-1.40000000e+00j,  0. +3.91886976e-16j,
       -1.6+1.40000000e+00j])

Разделим массив на чётные и нечётные элементы:

In [ ]:
ys[::2] , ys[1::2]

([-0.9, 0.7], [0.6, -0.8])

In [ ]:
def my_fft(ys):
  He = dft(ys[::2])
  Ho = dft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

Не рекурсивный метод:

In [ ]:
my_fft(ys)

array([-0.4+0.0000000e+00j, -1.6-1.4000000e+00j,  0. +2.4492936e-17j,
       -1.6+1.4000000e+00j])

In [ ]:
def my_fft(ys):
  if len(ys) == 1:
    return ys
  He = my_fft(ys[::2])
  Ho = my_fft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

Рекурсивный метод:

In [ ]:
my_fft(ys)

array([-0.4+0.0000000e+00j, -1.6-1.4000000e+00j,  0. +2.4492936e-17j,
       -1.6+1.4000000e+00j])